title: dneufeld notes
description: Notes on whatever I'm exploring right now
url: "https://dneufeld.github.io"
baseurl: ""
theme: minima
markdown: kramdown
cloudflare_web_analytics_token: ""
plugins:
  - jekyll-feed
show_excerpts: false
